---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# ggstoryboard

```{r}
library(ggplot2)
```





<!-- badges: start -->
<!-- badges: end -->

The goal of ggstoryboard is to show ggplot builds decision by decision.

```{r, eval = F}
devtools::create(path = "."
```


An example plot, chunk is called 'carsplot'

```{r carsplot}
ggplot(cars) + 
  aes(speed, dist) + 
  geom_point() + 
  aes(size = dist)
```


```{r code_to_storyboard}
code_to_storyboard <- function(code = NULL){

unconnected_code <- code |> 
  stringr::str_trim() |> 
  stringr::str_remove("\\+$")


partialcode <- c()

for(i in 1:length(code)){
  
  partialcode[i] <- paste(unconnected_code[1:i], collapse = " + ")
  
}


p <- list()  # Partial code sequence

for(i in 1:length(partialcode)){
  
  p[[i]] <- eval(parse(text = partialcode[i]))
  
 label <- ifelse(i > 1, paste("+", unconnected_code[i]), unconnected_code[i])
 
  p[[i]] <- p[[i]] + ggplot2::annotate(geom = "text",
                              x = I(.025),
                              y = I(.95), 
                              hjust = 0,
                              vjust = 1,
                              label = label,
                              color = "red"
                              )
  # 
}

patchwork::wrap_plots(p, ncol = 2)

}
```


```{r}
knitrExtra::chunk_code_get("carsplot") |> 
  code_to_storyboard()
```



```{r chunk_to_storyboard}
chunk_to_storyboard <- function(chunk_name){
  
  knitrExtra::chunk_code_get(chunk_name) |>
    code_to_storyboard()
  
}
```


```{r}
chunk_to_storyboard(chunk_name = "carsplot")
```


```{r}
knitrExtra:::chunk_to_r("chunk_to_storyboard")
knitrExtra:::chunk_to_r("code_to_storyboard")
```

```{r}
usethis::use_package("stringr")
usethis::use_package("ggplot2")
usethis::use_package("patchwork")
```


```{r, eval = F}
usethis::use_dev_package(package = "knitrExtra", remote = "EvaMaeRey/knitrExtra")
```

```{r, eval = F}
devtools::check(".")
```



